apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: rosnaldinho20/esquentak8s
        ports:
        - containerPort: 8080